server:
  port: 8080
spring:
  mvc:
    favicon:
      enabled: false
  http:
    encoding:
      charset: utf-8
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://192.144.175.184:3306/cloudglasses?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: cloudglasses2018
    password: J7QP6kEGbwY^stD5
    initialSize: 2
    maxActive: 10
    minIdle: 1
    maxWait: 60000
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 30000
    minEvictableIdleTimeMillis: 60000
    validationQuery: SELECT 1
    filters: wall,stat,slf4j,config
    initConnectionSqls: set NAMES utf8mb4;
  jpa:
    open-in-view: true
logging:
  level:
    com.cloudglasses: info